### ISSUE TITLE
Getting null pointer exception while showing progressbar

### ISSUE THREAD

**Issue by suresh777** [jpardogo/GoogleProgressBar#26]
java.lang.NullPointerException: Attempt to read from null array
                                                                  at com.jpardogo.android.googleprogressbar.library.ChromeFloatingCirclesDrawable.draw(ChromeFloatingCirclesDrawable.java:189)
                                                                  at android.widget.ProgressBar.drawTrack(ProgressBar.java:1803)
                                                                  at android.widget.ProgressBar.onDraw(ProgressBar.java:1770)
                                                                  at android.view.View.draw(View.java:17503)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16496)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16456)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16456)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16456)

**Comment by mdczaplicki** [comment]
Same here
